---
- include_vars: "{{ icescrum_version }}.yml"

- name: Ensure icescrum group is present.
  group:
    name: "{{ icescrum_group }}"
    state: present

- name: Ensure icescrum user is present.
  user:
    name: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
    state: present

- name: Ensure icescrum directories are present.
  file:
    path: "{{ item }}"
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
    mode: 0775
    state: directory
  with_items:
  - "{{ icescrum_install_dir }}"
  - "{{ icescrum_log_dir }}"

- name: Ensure server ID file is present.
  copy:
    dest: "{{ icescrum_install_dir }}/appID.txt"
    content: "{{ icescrum_appID }}"
  when: icescrum_appID is defined

- name: Ensure license directory is present.
  file:
    path: "{{ icescrum_install_dir }}/.icescrum"
    state: directory
    mode: 0750
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"

- name: Ensure license key is set.
  lineinfile:
    dest: "{{ icescrum_install_dir }}/.icescrum/license.key"
    line: "{{ icescrum_license_key }}"
    state: present
    create: yes
    mode: 0640
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
  when: icescrum_license_key is defined

- name: Ensure config.groovy is present.
  template:
    src: 'config.groovy.j2'
    dest: "{{ icescrum_config_dir }}/config.groovy"
    owner: "{{ icescrum_user }}"
    group: "{{ icescrum_group }}"
    mode: 0660
  register: icescrum_config_groovy

- include_tasks: mysql.yml
- include_tasks: installation_war.yml
- include_tasks: tomcat.yml
