- name: Mysql - Ensure database is created.
  mysql_db:
    name: "{{ icescrum_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_unicode_ci
    state: present

- name: Mysql - Ensure icescrum db user is present.
  mysql_user:
    name: "{{ icescrum_db_user }}"
    password: "{{ icescrum_db_password }}"
    priv: "{{ icescrum_db_name }}.*:ALL"
    state: present
