---
- getent: database="passwd" key="{{ icescrum_tomcat_user }}"

- name: Tomcat - Retrieve icescrum_tomcat_home value.
  set_fact:
    icescrum_tomcat_home: "{{ getent_passwd[icescrum_tomcat_user][4] }}"

- name: Tomcat - Ensure tomcat-jdbc.jar is absent (see https://www.icescrum.com/documentation/application-server/#application-server_1).
  file:
    path: "{{ icescrum_tomcat_home }}/lib/tomcat-jdbc.jar"
    state: absent

- name: Tomcat - Retrieve icescrum group members.
  getent: database=group key="{{ icescrum_group }}"

- name: Tomcat - Ensure tomcat user is in the icescrum group.
  user: name="{{ icescrum_tomcat_user }}" groups="{{ icescrum_group }}"
  when: not icescrum_tomcat_user in getent_group['{{ icescrum_group }}'][2]

- name: Tomcat - Ensure icescrum link into tomcat base is present.
  file:
    src: "{{ icescrum_install_dir }}/icescrum.war"
    dest: "{{ icescrum_tomcat_base }}/webapps/icescrum.war"
    state: link

- name: Tomcat - Ensure icescrum war is deployed.
  stat: path="{{ icescrum_tomcat_base }}/webapps/icescrum/WEB-INF/web.xml"
  register: icescrum_web

- name: Tomcat - Ensure setenv.sh is present.
  template: src='setenv.sh.j2' dest="{{ icescrum_tomcat_home }}/bin/setenv.sh" mode=0755
  when: icescrum_tomcat_configure
  register: icescrum_setenv

- name: Tomcat - Ensure server.xml is present.
  template: src='server.xml.j2' dest="{{ icescrum_tomcat_base }}/conf/server.xml"
  when: icescrum_tomcat_configure
  register: icescrum_server_xml

- name: Tomcat - Ensure icescrum is linked in tomcat.
  file:
    src: "{{ icescrum_install_dir }}"
    dest: "{{ icescrum_tomcat_home }}/icescrum"
    owner: "{{ icescrum_tomcat_user }}"
    state: link

- name: Tomcat - Restart if needed.
  service: name=tomcat7 state=restarted
  when: not icescrum_web.stat.exists or
        icescrum_setenv.changed or
        icescrum_config_groovy.changed or
        icescrum_server_xml.changed

- name: Tomcat - Ensure tomcat service is started.
  service:
    name: tomcat7
    state: started

- name: Tomcat - Ensure tomcat port is listen.
  wait_for: host=localhost port={{ icescrum_port  | default(8080) }} delay=10 state=drained